# 数据源配置
spring:
    datasource:
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/xxkwlkc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                user: root
                password: a123456
                uniqueResourceName: master
                driverClassName: com.mysql.cj.jdbc.Driver
                testQuery: SELECT 1 FROM DUAL
                minPoolSize: 10
                maxPoolSize: 20
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            queryTimeout: 6000
            asyncInit: true
            transactionQueryTimeout: 6000
            breakAfterAcquireFailure: false
            connectionErrorRetryAttempts: 3
            removeAbandoned: false
            removeAbandonedTimeoutMillis: 1800
            logAbandoned: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 1200000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: true
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username:
                login-password:
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true